apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ namespace }}
type: Opaque
stringData:
  superUserPassword: {{ secrets.postgresql.superuserpass }}
  replicationUserPassword: {{ secrets.postgresql.replicationpass }}