apiVersion: v1
kind: Service
metadata:
  name: traefik-websecure-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.32
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 80
    - protocol: TCP
      port: 443
      name: websecure
      targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.33
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik